archiveObserver 퍼포먼스 향상
sidewinderk/gbfTransKor pull request #45
Opened 2020-11-10 16:33 UTC by ajh1000

archiveObserver에 관해서는 거의 최대의 퍼포먼스까지 끌어올린것같음.
```
var config = {
    //attributes: true,
    childList: true,
    subtree: true,
    characterData: true
};
```
첫째줄``` //attributes: true,``` 이것만 주석처리하고 보니까 과도한 mutation이 일어나지않아서 깔끔하게 작동함.

트리 순회를 덜하게할려고 이것저것 알아보느라 이틀이 순삭됐는데 아무튼 여러가지 방법중에 저거 주석처리하는게 가장 깔끔한 결과를 냈음.

### 퍼포먼스 결과, 번역툴 미적용과 동일한 퍼포먼스 나옴.
![1](https://camo.githubusercontent.com/1bc2a32480d9b9c864a9649556dd16679332b33b4316bd2f6c7138d906f84c1b/68747470733a2f2f696d6775722e636f6d2f4c514f375869462e706e67)

<br>
<br>

### 테스트 환경
 메인화면 -> 퀘스트 -> 서포터 선택 화면 -> 전투 화면 -> 클리어 -> 메인화면

이렇게 새로고침 없이 수행했는데 미번역 되는 부분은 없었음. 

이번엔 진짜 완벽. 아마도.

2020-11-10 16:49 UTC, sidewinderk commented
수고하셨슴.
실제로 퍼포먼스가 더 좋아진걸 확인했고, 기본적으로 작동에 문제가 없는 걸로 보임.

다만 `ObserverArchive` 에서 주소체크가 빠져서, 
`doBattleTrans` 가 `false` 일 때(사용자가 전투 화면 번역을 켜지 않았을 때)
전투화면에서 아카이브 옵저버가 작동해서 번역이 되고, 퍼포먼스가 저해되는 문제가 있음.

어차피 전투화면에선 전담 Observer 를 쓰니까 `ObserverArchive` 는 단순하게 작동하지 않도록 해두고
필요한 element만 whitelist 방식으로 `ObserverBattle`에서 체크해주는게 좋을 것 같음.

2020-11-10 16:51 UTC, ajh1000 commented
아하 그럼 일단 닫고 내일 그거까지 구현할까하는데 어떰?

2020-11-10 16:54 UTC, sidewinderk commented
이걸 열어둔 상태로 작업해서 본인 repository에 push해도 여기에 자동으로 해당 commit이 추가되므로 닫아두지 않고 열어둬도 될 것 같음.

2020-11-10 16:55 UTC, ajh1000 commented
아 ㅇㅋㅇㅋ!! 알겠음

2020-11-10 17:07 UTC, ajh1000 commented
음 지금 다시 봤는데 주소체크 들어가있어서 전투중에는 archiveObserver 가 작동 안하게끔 되있는것같음.
```
    if (doBattleTrans) {
        if (doc.URL.includes('#raid')) {
            archiveObserver.disconnect();
            window.setTimeout(ObserverArchive, generalConfig.refreshRate);
            return;
        }
```

전투해봤을땐 성능 저하가 없는것같은데 정말 정말 미안하지만 혹시 다시 봐줄수있음?

2020-11-10 17:09 UTC, ajh1000 commented
아 먼지 알것같다. 다시 해보겠음

2020-11-11 01:12 UTC, ajh1000 commented
오케이 메인화면에서 ```doBattleTrans``` 껐다 켜보면서 테스트해봤고, 전투화면에서도 켜보고 테스트했을때 ```ObserverArchive, ObserverImage, ObserverImageDIV``` 가 작동하지 않았음.

2020-11-11 18:07 UTC, sidewinderk requested changes
여전히 전투화면에서 전투중 번역 옵션을 꺼둔 상태에서도 번역이 이루어짐.
기본적으로 `ObserverArchive`, `ObserverImage`, `ObserverImageDIV` 위 세 함수는 전투 화면에서 작동하지 않도록 해둬서 전투 번역 관련 함수와 일반번역 관련 함수를 구분해서 사용하고자함.

2020-11-11 18:07 UTC, sidewinderk commented on content.js
> +        window.setTimeout(ObserverArchive, generalConfig.refreshRate);
```suggestion
    if(doc.URL.includes('#raid')){
        ImageObserver.disconnect();
        archiveObserver.disconnect();
        window.setTimeout(ObserverImageDIV, generalConfig.refreshRate);
```

전투 url 일때는 작동시키지 않음.

2020-11-11 18:07 UTC, sidewinderk commented on gbfTrans.js
> +        archiveObserver.disconnect();
```suggestion
    if(doc.URL.includes('#raid')){
        archiveObserver.disconnect();
```

2020-11-11 18:07 UTC, sidewinderk commented on gbfTrans.js
> +        window.setTimeout(ObserverArchive, generalConfig.refreshRate);
```suggestion
    if(doc.URL.includes('#raid')){
        ImageObserver.disconnect();
        archiveObserver.disconnect();
        window.setTimeout(ObserverImage, generalConfig.refreshRate);
```

2020-11-11 18:07 UTC, sidewinderk commented on gbfTrans.js
> +        window.setTimeout(ObserverArchive, generalConfig.refreshRate);
```suggestion
    if(doc.URL.includes('#raid')){
        ImageObserver.disconnect();
        archiveObserver.disconnect();
        window.setTimeout(ObserverImageDIV, generalConfig.refreshRate);
```

2020-11-11 18:07 UTC, sidewinderk commented on gbfTrans_test.js
> +        archiveObserver.disconnect();
```suggestion
    if(doc.URL.includes('#raid')){
        archiveObserver.disconnect();
```

2020-11-11 18:07 UTC, sidewinderk commented on gbfTrans_test.js
> +        window.setTimeout(ObserverArchive, generalConfig.refreshRate);
```suggestion
    if(doc.URL.includes('#raid')){
        ImageObserver.disconnect();
        archiveObserver.disconnect();
        window.setTimeout(ObserverImage, generalConfig.refreshRate);
```

2020-11-11 18:07 UTC, sidewinderk commented on gbfTrans_test.js
> +        window.setTimeout(ObserverArchive, generalConfig.refreshRate);
```suggestion
    if(doc.URL.includes('#raid')){
        ImageObserver.disconnect();
        archiveObserver.disconnect();
        window.setTimeout(ObserverImageDIV, generalConfig.refreshRate);
```

2020-11-12 02:32 UTC, ajh1000 commented
흠.. 내 코드에서는 버그를 재현할수없었음. 그래도 님 코드가 더 적절해보여서 변경사항 커밋했음.
수고하셨음!

2020-11-12 12:17 UTC, sidewinderk commented
해결 된것으로 보임 수고하셨슴

2020-11-12 12:17 UTC, merged